import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { tajawal } from "@/fonts";

export const metadata: Metadata = {
  title: "Kosh Gents Saloon - Financial Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Assuming that you can toggle the language dynamically
	const isArabic = true; // Set this based on your language logic

  return (
    <html 
      lang={isArabic ? 'ar' : 'en'}
      dir={isArabic ? 'rtl' : 'ltr'}
      suppressHydrationWarning
    >
      <body
        className={`${tajawal.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <ModeToggle/>
          </ThemeProvider>
      </body>
    </html>
  );
}
